### PR TITLE
Trying to solve #20

### PR DESCRIPTION
**Pull request by enumag**

### CODE REVIEW

**Comment by enumag** [comment]
I've refactored the doAdd function, here is what I've changed:

1) Removed usage of the tmp element for finding the ID. Basically I've replaced this

```
var id = tmp.html(code).find('[id]').first().attr('id');
tmp.empty();
```

with this

```
var id = code.find('[id]').first().attr('id');
```

Should be equivalent in my opinion.

2) Moved the essential code outside of a loop (it was only used onetime anyway because of the `break;`).

3) Replaced the for loop with do-while.

4) The loop no longer checks `settings.max`.

5) Added new option `initial_index` which allows me to fix my use-case. With this I should be able to fix #20 by emulating PHP's behavior for generating new indexes.

**Comment by enumag** [comment]
@ninsuo Don't merge this yet please. Just tell me your opinion about the changes for now. Thanks.

**Comment by ninsuo** [comment]
Hello,

- About 1) this was fixed in #37 ( `$(code).find()` instead of using `.html().find()` )

- About 2), i really like the initial_index stuff to avoid that ugly loop; in your implementation it is not initialized with the right number of elements contained in the collection at the beginning, but the idea is here

- About 3), that's right, if everything is outside the loop a do/while makes more sense - but i'm sure with 2) implemented we could even remove the loop entirely

- For 4), you're right, even if it looks to make sense (as we can't have more elments than max), that's useless

Sorry for the very long delay. Will think about your PR now.

**Comment by enumag** [comment]
Actually I found out this doesn't really solve my case and I managed to fix it otherwise (without modifications to this package).

**Comment by ninsuo** [comment]
Thank you anyway, I will do some fixes on my side regarding your ideas.

**Pull request closed without merging**
