### PR TITLE
Fix: Issue where enabling add_at_the_end caused no add buttons to appear at all

### PR DESCRIPTION
**Pull request by themainframe**
The behaviour of `add_at_the_end` seems incorrect. Currently, Add buttons will simply not appear if `add_at_the_end` is `true`.

### CODE REVIEW

**Comment by enumag** [comment]
This bug is probably from https://github.com/ninsuo/symfony-collection/pull/21. Merging this would probably cause the bug I tried to fix there once again.

**Comment by enumag** [comment]
Also with `add_at_the_end` set to `true` the button does appear for me. Not sure where is the difference.

**Comment by themainframe** [comment]
Is this on `master`? The code currently seems to prohibit the *Add* button from ever appearing if `add_at_the_end` is `true`:

```javascript
{'enabled': settings.allow_add && !settings.add_at_the_end  ...
```

**Comment by enumag** [comment]
Yeah, I'm using master. For me it only prevents the appearance of buttons after each item but the button at the end works fine.

**Comment by enumag** [comment]
Oh maybe it works for me because I added the button manually in the template. Do you want to try and fix it yourself or should I look into it?

**Comment by themainframe** [comment]
However you'd like to proceed! I was just passing through and ran into this one. Looks like the interplay of logic between `add_at_the_end`, `allow_add`, `hide_useless_buttons` is quite (or needs to be quite) complex. You probably have a better understanding of it than I do so perhaps it's best if you look into it?

**Comment by enumag** [comment]
Ok, I'll try. Thanks for the report!

**Comment by enumag** [comment]
Sadly I'm unable to reproduce the bug. The button that should appear at the end doesn't seem dependent on the change from #21. See https://github.com/ninsuo/symfony-collection/blob/master/jquery.collection.js#L303-L312.

Can you post your JS configuration of this plugin + your twig template for collection type?

**Comment by ninsuo** [comment]
Hello,

Sorry for the late answer, I was very busy those days.

I also can't reproduce this issue, can you please give more context? 
- How are you initializing your collection?
- Are you using a custom form theme, and if yes can you provide it?

Thanks,
A

**Comment by paulgv** [comment]
Hi,
I have the same issue. When using a custom theme along with the `add_at_the_end` option set to `true`, the add button only appears when the collection is empty, as soon as I add an element, the button disappears and won't show again unless I remove all items from the collection.

Here is my custom prototype theme :

```
{% block _work_order_report_equipment_details_entry_row %}
    <div class="row">
        <div class="col-md-2">
            {{ form_row(form.qty) }}
        </div>
        <div class="col-md-9">
            {{ form_row(form.part_description) }}
        </div>
        <div class="col-md-1">
            <label class="invisible">Remove</label>
            <a href="#" class="collection-delete btn btn-default">
                <i class="glyphicon glyphicon-minus"></i>
            </a>
        </div>
    </div>
{% endblock %}
```
And the initialization script :

```
<script type="text/javascript">
    $(function () {
        $('.collection-type').collection({
            init_with_n_elements: 1,
            allow_up: false,
            allow_down: false,
            up: '<a href="#" class="btn btn-default"><span class="glyphicon glyphicon-arrow-up"></span></a>',
            down: '<a href="#" class="btn btn-default"><span class="glyphicon glyphicon-arrow-down"></span></a>',
            add: '<a href="#" class="btn btn-default"><span class="glyphicon glyphicon-plus"></span></a>',
            delete: '<a href="#" class="btn btn-default"><span class="glyphicon glyphicon-trash"></span></a>',
            add_at_the_end: true
        });
    });
</script>
```

Thanks for the plugin, it saved me a lot of time. A fix for this issue would make it even more awesome :D

**Comment by ninsuo** [comment]
I'll have a look.

It would help me a lot if you were able to reproduce this issue on the [demo website](https://github.com/ninsuo/symfony-collection-demo) so I'll have a runnable sample.

**Comment by paulgv** [comment]
Hi,
Very simple sample here paulgv/symfony-collection-demo@a47b075e17639c105296db0399b487895685c905
I simply set the option to `true` in the custom form theme example.
Also on another note, I've been having a lot of trouble rendering a collection as a table : the page simply never finished loading with `init_with_n_elements > 0`. I ended up fixing the issue by setting the `elements_selector` to `> tr`. I haven't seen any doc on this option, it might be worth mentioning it somewhere since it seems pretty useful :D

**Comment by ninsuo** [comment]
Thanks, I'll check this :)

**Comment by ninsuo** [comment]
I'm on it, should be fixed today.

**Comment by ninsuo** [comment]
Enjoy!
http://symfony-collection.fuz.org/advanced/customFormThemeAddBottom

**Pull request closed without merging**
