### PR TITLE
Sorting based on floats instead of string value

### PR DESCRIPTION
**Pull request by leroy0211**
This is the fix for the initial sort issue. #70

### CODE REVIEW

**Comment by ninsuo** [comment]
Hello,

Thanks a lot for your contribution.

Can you just replace bitwise or (`|`) by a logical or `||`?

A

**Comment by ninsuo** [comment]
In fact, you can even remove this fallback.

If an element at index 5 has position 0, its position will become 5.

**Comment by leroy0211** [comment]
You are right. I just resetted the head back to the previous commit.

**Comment by ninsuo** [comment]
Great!

Thanks again for your contribution.

A

**Pull request merged**
