### PR TITLE
Fix indentation & Add some options

### PR DESCRIPTION
**Pull request by enumag**
In order to use this script I had to update it a bit. In order to preserve backward compatibility I added new options and set their default values to be compatible with previous behavior.

Also indentation looked wrong so I fixed that as well.

### CODE REVIEW

**Comment by ninsuo** [comment]
Thanks for your contribution.

Can you please update the README.md file to document the 2 new options?
I'll handle the demo website.

**Comment by enumag** [comment]
Thanks for your feedback. I'll update the readme file when I have time. I need to check if I really need both of the new options first.

**Comment by enumag** [comment]
@ninsuo I've reworked it to only add one option and small fix which allows me to not need the other one. It should not contain any BC break but I do recommend to test it on your demo site before meging to be sure.

**Comment by ninsuo** [comment]
Thanks i'l check that :).

**Comment by ninsuo** [comment]
I just checked, this is good.
Thanks!

**Comment by ninsuo** [comment]
Demo implemented here:
http://symfony-collection.fuz.org/options/hideMoveUpDown

**Comment by enumag** [comment]
Thank you!

**Pull request merged**
